/*
 Navicat Premium Data Transfer

 Source Server         : --
 Source Server Type    : MySQL
 Source Server Version : 50728 (5.7.28-31)
 Source Host           : localhost:3206
 Source Schema         : a1

 Target Server Type    : MySQL
 Target Server Version : 50728 (5.7.28-31)
 File Encoding         : 65001

 Date: 01/03/2024 16:05:08
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for projects
-- ----------------------------
DROP TABLE IF EXISTS `projects`;
CREATE TABLE `projects` (
                            `id` varchar(36) NOT NULL,
                            `name` varchar(256) CHARACTER SET utf8mb4 NOT NULL,
                            `ip` varchar(50) NOT NULL,
                            `time` bigint(20) NOT NULL,
                            `properties` longtext CHARACTER SET utf8mb4 NOT NULL,
                            `templateViewCount` bigint(20) NOT NULL DEFAULT '0',
                            PRIMARY KEY (`id`),
                            UNIQUE KEY `name` (`name`),
                            KEY `ipTimeIndex` (`ip`,`time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

-- ----------------------------
-- Records of projects
-- ----------------------------
BEGIN;
INSERT INTO `projects` (`id`, `name`, `ip`, `time`, `properties`, `templateViewCount`) VALUES ('p_ehkpgvr6wdts', 'Block Card', '127.0.0.1', 1743490049062, '{\"chatBotSettings\":{\"minimize\":false,\"survey\":false,\"upload\":true},\"createBy\":\"1\",\"createTime\":\"1743490049040\",\"fallback\":\"Lame! We got a glitch, please try again later.\",\"fallbackType\":\"text\",\"faqNlpModel\":true,\"faqNlpShowRelatedQuestions\":false,\"faqUseNlpAnswer\":false,\"flowNlpModel\":true,\"locale\":\"zh\",\"replyKnowledgeBaseStrict\":true,\"schedule\":\"priority\",\"shared\":false,\"showKnowledgeBaseSource\":false,\"showSubNodesAsOptional\":\"all\",\"type\":\"llm\",\"updateBy\":\"1\",\"updateTime\":\"1743490108140\",\"viewable\":true,\"welcome\":\"Hello, I am your intelligent assistant. What can I do for you?\"}', 0);
INSERT INTO `projects` (`id`, `name`, `ip`, `time`, `properties`, `templateViewCount`) VALUES ('p_ehkphgq3pnuo', 'Survey', '127.0.0.1', 1743490059926, '{\"chatBotSettings\":{\"minimize\":false,\"survey\":false,\"upload\":true},\"createBy\":\"1\",\"createTime\":\"1743490059923\",\"fallback\":\"Lame! We got a glitch, please try again later.\",\"fallbackType\":\"text\",\"faqNlpModel\":true,\"faqNlpShowRelatedQuestions\":false,\"faqUseNlpAnswer\":false,\"flowNlpModel\":true,\"locale\":\"zh\",\"replyKnowledgeBaseStrict\":true,\"schedule\":\"priority\",\"shared\":false,\"showKnowledgeBaseSource\":false,\"showSubNodesAsOptional\":\"all\",\"type\":\"llm\",\"updateBy\":\"1\",\"updateTime\":\"1743490103525\",\"viewable\":true,\"welcome\":\"Hello! I\'d like to ask you few questions about your recent experience with our customer service team. Your feedback is very important to us.\"}', 0);
INSERT INTO `projects` (`id`, `name`, `ip`, `time`, `properties`, `templateViewCount`) VALUES ('p_ehkpj0ymf0u8', 'Transfer Money', '127.0.0.1', 1743490089112, '{\"chatBotSettings\":{\"minimize\":false,\"survey\":false,\"upload\":true},\"createBy\":\"1\",\"createTime\":\"1743490089109\",\"fallback\":\"Lame! We got a glitch, please try again later.\",\"fallbackType\":\"text\",\"faqNlpModel\":true,\"faqNlpShowRelatedQuestions\":false,\"faqUseNlpAnswer\":false,\"flowNlpModel\":true,\"locale\":\"zh\",\"replyKnowledgeBaseStrict\":true,\"schedule\":\"priority\",\"shared\":false,\"showKnowledgeBaseSource\":false,\"showSubNodesAsOptional\":\"all\",\"type\":\"llm\",\"updateBy\":\"1\",\"updateTime\":\"1743490095770\",\"viewable\":true,\"welcome\":\"Hello! I’m your smart assistant for handling money transfers. Please provide the recipient\'s details and the amount you’d like to transfer, and I’ll guide you through the process securely.\"}', 0);
COMMIT;

-- ----------------------------
-- Table structure for project_components
-- ----------------------------
DROP TABLE IF EXISTS `project_components`;
CREATE TABLE `project_components` (
  `id` varchar(64) NOT NULL,
  `projectId` varchar(60) NOT NULL,
  `rootComponentId` varchar(60) DEFAULT NULL,
  `type` varchar(36) NOT NULL,
  `properties` longtext CHARACTER SET utf8mb4,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

-- ----------------------------
-- Records of project_components
-- ----------------------------
BEGIN;
INSERT INTO `project_components` (`id`, `projectId`, `rootComponentId`, `type`, `properties`) VALUES ('cp_ehkpgvrodo8w', 'p_ehkpgvr6wdts', 'c_ehkpgvrlvrwg', 'bot', '{\"createBy\":\"0\",\"createTime\":\"1743490049047\",\"data\":{\"data\":{\"responses\":[{\"content\":{\"text\":\"Okay, we can block a card. Let\'s do it in a few steps\"},\"delay\":\"500\",\"id\":\"85c7e9b3c51d4be5b797242342d9b382\",\"type\":\"text\"}]},\"parentId\":\"c_ehkpgvrlvrwg\"},\"nextChildNo\":0,\"no\":0,\"updateBy\":\"0\",\"updateTime\":\"0\"}');
INSERT INTO `project_components` (`id`, `projectId`, `rootComponentId`, `type`, `properties`) VALUES ('cp_ehkpgvrodo8x', 'p_ehkpgvr6wdts', 'c_ehkpgvrlvrwg', 'bot', '{\"createBy\":\"0\",\"createTime\":\"1743490049047\",\"data\":{\"data\":{\"responses\":[{\"content\":{\"text\":\"Please tell us the reason for blocking\"},\"delay\":\"500\",\"id\":\"cfdee48f553241d1accfef391bce9cc0\",\"type\":\"text\"}]},\"parentId\":\"cp_ehkpgvrodo8w\"},\"nextChildNo\":0,\"no\":0,\"updateBy\":\"0\",\"updateTime\":\"0\"}');
INSERT INTO `project_components` (`id`, `projectId`, `rootComponentId`, `type`, `properties`) VALUES ('cp_ehkpgvrqvklc', 'p_ehkpgvr6wdts', 'c_ehkpgvrlvrwg', 'user', '{\"createBy\":\"0\",\"createTime\":\"1743490049048\",\"data\":{\"data\":{\"enable\":true,\"examples\":[{\"text\":\"My card is damaged\"}],\"labels\":[],\"name\":\"My card is damaged\"},\"parentId\":\"cp_ehkpgvrodo8x\"},\"nextChildNo\":0,\"no\":0,\"updateBy\":\"0\",\"updateTime\":\"0\"}');
INSERT INTO `project_components` (`id`, `projectId`, `rootComponentId`, `type`, `properties`) VALUES ('cp_ehkpgvrqvkld', 'p_ehkpgvr6wdts', 'c_ehkpgvrlvrwg', 'bot', '{\"createBy\":\"0\",\"createTime\":\"1743490049048\",\"data\":{\"data\":{\"responses\":[{\"content\":{\"text\":\"Thank you for letting us know. I\'m sorry to hear the card was {reason_for_blocking}\"},\"delay\":\"500\",\"id\":\"cd66b979058b47d48210bf6e076ddcff\",\"type\":\"text\"}]},\"parentId\":\"cp_ehkpgvrqvklc\"},\"nextChildNo\":0,\"no\":0,\"updateBy\":\"0\",\"updateTime\":\"0\"}');
INSERT INTO `project_components` (`id`, `projectId`, `rootComponentId`, `type`, `properties`) VALUES ('cp_ehkpgvrqvkle', 'p_ehkpgvr6wdts', 'c_ehkpgvrlvrwg', 'bot', '{\"createBy\":\"0\",\"createTime\":\"1743490049048\",\"data\":{\"data\":{\"responses\":[{\"content\":{\"text\":\"Would you like to be issued a new card?\"},\"delay\":\"500\",\"id\":\"5ebf41de223943ce86e2014e9f450688\",\"type\":\"text\"}]},\"parentId\":\"cp_ehkpgvrqvkld\"},\"nextChildNo\":0,\"no\":0,\"updateBy\":\"0\",\"updateTime\":\"0\"}');
INSERT INTO `project_components` (`id`, `projectId`, `rootComponentId`, `type`, `properties`) VALUES ('cp_ehkpgvrqvklf', 'p_ehkpgvr6wdts', 'c_ehkpgvrlvrwg', 'user', '{\"createBy\":\"0\",\"createTime\":\"1743490049048\",\"data\":{\"data\":{\"enable\":true,\"examples\":[{\"text\":\"Yes\"},{\"text\":\" send me a new card\"}],\"labels\":[],\"name\":\"Yes\"},\"parentId\":\"cp_ehkpgvrqvkle\"},\"nextChildNo\":0,\"no\":0,\"updateBy\":\"0\",\"updateTime\":\"0\"}');
INSERT INTO `project_components` (`id`, `projectId`, `rootComponentId`, `type`, `properties`) VALUES ('cp_ehkpgvrqvklg', 'p_ehkpgvr6wdts', 'c_ehkpgvrlvrwg', 'bot', '{\"createBy\":\"0\",\"createTime\":\"1743490049048\",\"data\":{\"data\":{\"responses\":[{\"content\":{\"text\":\"Here is your new card.\"},\"delay\":\"500\",\"id\":\"fea49a02065b4a02b4b4da45818176c2\",\"type\":\"text\"}]},\"parentId\":\"cp_ehkpgvrqvklf\"},\"nextChildNo\":0,\"no\":0,\"updateBy\":\"0\",\"updateTime\":\"0\"}');
INSERT INTO `project_components` (`id`, `projectId`, `rootComponentId`, `type`, `properties`) VALUES ('cp_ehkpgvrqvklh', 'p_ehkpgvr6wdts', 'c_ehkpgvrlvrwg', 'user', '{\"createBy\":\"0\",\"createTime\":\"1743490049048\",\"data\":{\"data\":{\"enable\":true,\"examples\":[{\"text\":\"No\"}],\"labels\":[],\"name\":\"No\"},\"parentId\":\"cp_ehkpgvrqvkle\"},\"nextChildNo\":0,\"no\":0,\"updateBy\":\"0\",\"updateTime\":\"0\"}');
INSERT INTO `project_components` (`id`, `projectId`, `rootComponentId`, `type`, `properties`) VALUES ('cp_ehkpgvrqvkli', 'p_ehkpgvr6wdts', 'c_ehkpgvrlvrwg', 'bot', '{\"createBy\":\"0\",\"createTime\":\"1743490049048\",\"data\":{\"data\":{\"responses\":[{\"content\":{\"text\":\"Now, you card already blocked!\"},\"delay\":\"500\",\"id\":\"b112552ff4ae4f2ebf0e3eeb93e7fa77\",\"type\":\"text\"}]},\"parentId\":\"cp_ehkpgvrqvklh\"},\"nextChildNo\":0,\"no\":0,\"updateBy\":\"0\",\"updateTime\":\"0\"}');
INSERT INTO `project_components` (`id`, `projectId`, `rootComponentId`, `type`, `properties`) VALUES ('cp_ehkpgvrqvklj', 'p_ehkpgvr6wdts', 'c_ehkpgvrlvrwg', 'user', '{\"createBy\":\"0\",\"createTime\":\"1743490049048\",\"data\":{\"data\":{\"enable\":true,\"examples\":[{\"text\":\"I lost my card\"}],\"labels\":[],\"name\":\"I lost my card\"},\"parentId\":\"cp_ehkpgvrodo8x\"},\"nextChildNo\":0,\"no\":0,\"updateBy\":\"0\",\"updateTime\":\"0\"}');
INSERT INTO `project_components` (`id`, `projectId`, `rootComponentId`, `type`, `properties`) VALUES ('cp_ehkpgvrqvklk', 'p_ehkpgvr6wdts', 'c_ehkpgvrlvrwg', 'bot', '{\"createBy\":\"0\",\"createTime\":\"1743490049048\",\"data\":{\"data\":{\"responses\":[{\"content\":{\"text\":\"As your card was potentially stolen, it\'s crucial to report this incident to the authorities. Please contact your local law enforcement agency immediately.\"},\"delay\":\"500\",\"id\":\"ccf26f649f6f45bc9c06eca79fff824d\",\"type\":\"text\"}]},\"parentId\":\"cp_ehkpgvrqvklj\"},\"nextChildNo\":0,\"no\":0,\"updateBy\":\"0\",\"updateTime\":\"0\"}');
INSERT INTO `project_components` (`id`, `projectId`, `rootComponentId`, `type`, `properties`) VALUES ('cp_ehkpgvs5uyo0', 'p_ehkpgvr6wdts', 'c_ehkpgvrlvrwg', 'goto', '{\"createBy\":\"0\",\"createTime\":\"1743490049054\",\"data\":{\"data\":{\"linkId\":\"cp_ehkpgvrqvkli\"},\"parentId\":\"cp_ehkpgvrqvklk\"},\"nextChildNo\":0,\"no\":0,\"updateBy\":\"0\",\"updateTime\":\"0\"}');
INSERT INTO `project_components` (`id`, `projectId`, `rootComponentId`, `type`, `properties`) VALUES ('cp_ehkpgvs5uyo1', 'p_ehkpgvr6wdts', 'c_ehkpgvrlvrwg', 'user', '{\"createBy\":\"0\",\"createTime\":\"1743490049054\",\"data\":{\"data\":{\"enable\":true,\"examples\":[{\"text\":\"I\'m moving to a new address\"}],\"labels\":[],\"name\":\"I\'m moving to a new address\"},\"parentId\":\"cp_ehkpgvrodo8x\"},\"nextChildNo\":0,\"no\":0,\"updateBy\":\"0\",\"updateTime\":\"0\"}');
INSERT INTO `project_components` (`id`, `projectId`, `rootComponentId`, `type`, `properties`) VALUES ('cp_ehkpgvs5uyo2', 'p_ehkpgvr6wdts', 'c_ehkpgvrlvrwg', 'bot', '{\"createBy\":\"0\",\"createTime\":\"1743490049054\",\"data\":{\"data\":{\"responses\":[{\"content\":{\"text\":\"Thanks for informing us about moving.\"},\"delay\":\"500\",\"id\":\"cfc04a70d56949948bd348f361ae194d\",\"type\":\"text\"}]},\"parentId\":\"cp_ehkpgvs5uyo1\"},\"nextChildNo\":0,\"no\":0,\"updateBy\":\"0\",\"updateTime\":\"0\"}');
INSERT INTO `project_components` (`id`, `projectId`, `rootComponentId`, `type`, `properties`) VALUES ('cp_ehkpgvs5uyo3', 'p_ehkpgvr6wdts', 'c_ehkpgvrlvrwg', 'goto', '{\"createBy\":\"0\",\"createTime\":\"1743490049054\",\"data\":{\"data\":{\"linkId\":\"cp_ehkpgvrqvkli\"},\"parentId\":\"cp_ehkpgvs5uyo2\"},\"nextChildNo\":0,\"no\":0,\"updateBy\":\"0\",\"updateTime\":\"0\"}');
INSERT INTO `project_components` (`id`, `projectId`, `rootComponentId`, `type`, `properties`) VALUES ('cp_ehkpgvs5uyo4', 'p_ehkpgvr6wdts', 'c_ehkpgvrlvrwg', 'user', '{\"createBy\":\"0\",\"createTime\":\"1743490049054\",\"data\":{\"data\":{\"enable\":true,\"examples\":[{\"text\":\"Other\"}],\"labels\":[],\"name\":\"Other\"},\"parentId\":\"cp_ehkpgvrodo8x\"},\"nextChildNo\":0,\"no\":0,\"updateBy\":\"0\",\"updateTime\":\"0\"}');
INSERT INTO `project_components` (`id`, `projectId`, `rootComponentId`, `type`, `properties`) VALUES ('cp_ehkpgvs5uyo5', 'p_ehkpgvr6wdts', 'c_ehkpgvrlvrwg', 'bot', '{\"createBy\":\"0\",\"createTime\":\"1743490049054\",\"data\":{\"data\":{\"responses\":[{\"content\":{\"text\":\"Should you require further assistance, please contact our support team at 020 7777 7777. Thank you for being a valued customer.\"},\"delay\":\"500\",\"id\":\"2e02c6dd52e34f51b3abb18779c1c4d8\",\"type\":\"text\"}]},\"parentId\":\"cp_ehkpgvs5uyo4\"},\"nextChildNo\":0,\"no\":0,\"updateBy\":\"0\",\"updateTime\":\"0\"}');
INSERT INTO `project_components` (`id`, `projectId`, `rootComponentId`, `type`, `properties`) VALUES ('cp_ehkphgq67k74', 'p_ehkphgq3pnuo', 'c_ehkphgq3pnup', 'gpt', '{\"createBy\":\"0\",\"createTime\":\"1743490059924\",\"data\":{\"data\":{\"description\":\"You are a survey bot\",\"functionCalling\":[],\"name\":\"Survey\",\"prompt\":\"You will be presented with a survey. Please chat with the user and ask them the questions in order. Do not provide the entire survey at once.\\n\\nSurvey:\\n\\nDid you find our customer service team helpful? (Yes/No)\\nHow would you rate your overall satisfaction with our customer service? (1 - Very Dissatisfied to 5 - Very Satisfied)\\nWas your issue resolved by our customer service team? (Yes/No) If Yes, proceed to question 4.\\nWhich of the following best describes the response time of our customer service team? A) Very Fast B) Fast C) Average D) Slow E) Very Slow\\nWhat did you like most about your experience with our customer service?\",\"slots\":[]},\"parentId\":\"c_ehkphgq3pnup\"},\"nextChildNo\":0,\"no\":0,\"updateBy\":\"0\",\"updateTime\":\"0\"}');
INSERT INTO `project_components` (`id`, `projectId`, `rootComponentId`, `type`, `properties`) VALUES ('cp_ehkpj0yowx6o', 'p_ehkpj0ymf0u8', NULL, 'any', '{\"createBy\":\"0\",\"createTime\":\"1743490089111\",\"data\":{\"influenceConversation\":false,\"slotType\":\"string\",\"defaultValue\":\"\",\"defaultValueEnable\":false,\"display\":\"recipient\",\"name\":\"recipient\",\"enumEnable\":false,\"defaultValueType\":\"set\",\"enum\":[]},\"nextChildNo\":0,\"no\":0,\"updateBy\":\"0\",\"updateTime\":\"0\"}');
INSERT INTO `project_components` (`id`, `projectId`, `rootComponentId`, `type`, `properties`) VALUES ('cp_ehkpj0yowx6p', 'p_ehkpj0ymf0u8', NULL, 'any', '{\"createBy\":\"0\",\"createTime\":\"1743490089111\",\"data\":{\"influenceConversation\":false,\"slotType\":\"string\",\"defaultValue\":\"\",\"defaultValueEnable\":false,\"display\":\"amount_of_money\",\"name\":\"amount_of_money\",\"enumEnable\":false,\"defaultValueType\":\"set\",\"enum\":[]},\"nextChildNo\":0,\"no\":0,\"updateBy\":\"0\",\"updateTime\":\"0\"}');
INSERT INTO `project_components` (`id`, `projectId`, `rootComponentId`, `type`, `properties`) VALUES ('cp_ehkpj0yretj4', 'p_ehkpj0ymf0u8', 'c_ehkpj0yowx6q', 'gpt', '{\"createBy\":\"0\",\"createTime\":\"1743490089111\",\"data\":{\"data\":{\"description\":\"This is an agent for transfer money request.\",\"functionCalling\":[{\"code\":\"def submit_transaction(amount_of_money, recipient):\\n    account_balance= 1000.0\\n    \\n    account_balance -= amount_of_money\\n\\n    # 记录交易信息\\n    transaction = {\\n        \\\"amount_of_money\\\": amount_of_money,\\n        \\\"recipient\\\": recipient,\\n        \\\"transaction_time\\\": \\\"CURRENT_TIMESTAMP\\\"  # 模拟时间戳\\n    }\\n\\n    # 打印成功信息\\n    print(f\\\"Transaction successful. Money: {amount_of_money}, Recipient: {recipient}\\\")\\n    print(f\\\"Updated account balance: {account_balance}\\\")\\n    return [{\\\"text\\\":f\\\"Transaction successful. Money: {amount_of_money}, Recipient: {recipient}\\\"}]\\n\",\"name\":\"submit_transaction\"},{\"code\":\"def validate_account_funds(amount_of_money):\\n    account_balance = 1000.0  # 假设初始账户余额为 1000\\n\\n    if account_balance >= amount_of_money:\\n        print(\\\"Sufficient funds.\\\")\\n        return True\\n    else:\\n        print(\\\"Insufficient funds.\\\")\\n        return False\\n\\n\",\"name\":\"validate_account_funds\"}],\"name\":\"transfer_money\",\"prompt\":\"You are a smart agent for handling transferring money request. When user ask for transferring money, it is necessary to sequentially collect the recipient\'s information and the transfer amount. Then, the function \\\"validate_account_funds\\\" should be called to check whether the account balance is sufficient to cover the transfer. If the balance is insufficient, it should return to the step of requesting the transfer amount. Finally, before proceeding with the transfer, confirm with the user whether the transfer should be made and then call \\\"submit_transaction\\\".\",\"slots\":[{\"slotId\":\"cp_ehkpj0yowx6o\",\"type\":\"from_entity\"},{\"slotId\":\"cp_ehkpj0yowx6p\",\"type\":\"from_entity\"}]},\"parentId\":\"c_ehkpj0yowx6q\"},\"nextChildNo\":0,\"no\":0,\"updateBy\":\"0\",\"updateTime\":\"0\"}');
INSERT INTO `project_components` (`id`, `projectId`, `rootComponentId`, `type`, `properties`) VALUES ('c_ehkpgvrlvrwg', 'p_ehkpgvr6wdts', NULL, 'conversation', '{\"createBy\":\"0\",\"createTime\":\"1743490049047\",\"data\":{\"data\":{\"hidden\":false,\"isReady\":false,\"name\":\"Block_Card\",\"description\":\"Block or freeze a user\'s debit or credit card\",\"type\":\"flowAgent\"},\"isReady\":true},\"nextChildNo\":0,\"no\":0,\"updateBy\":\"0\",\"updateTime\":\"0\"}');
INSERT INTO `project_components` (`id`, `projectId`, `rootComponentId`, `type`, `properties`) VALUES ('c_ehkphgq3pnup', 'p_ehkphgq3pnuo', NULL, 'conversation', '{\"createBy\":\"0\",\"createTime\":\"1743490059923\",\"data\":{\"data\":{\"hidden\":false,\"isReady\":false,\"name\":\"Survey\",\"description\":\"You are a survey bot\",\"type\":\"llmAgent\"},\"isReady\":true},\"nextChildNo\":0,\"no\":0,\"updateBy\":\"0\",\"updateTime\":\"0\"}');
INSERT INTO `project_components` (`id`, `projectId`, `rootComponentId`, `type`, `properties`) VALUES ('c_ehkpj0yowx6q', 'p_ehkpj0ymf0u8', NULL, 'conversation', '{\"createBy\":\"0\",\"createTime\":\"1743490089110\",\"data\":{\"data\":{\"hidden\":false,\"isReady\":false,\"name\":\"transfer_money\",\"description\":\"This is an agent for transfer money request.\",\"type\":\"llmAgent\"},\"isReady\":true},\"nextChildNo\":0,\"no\":0,\"updateBy\":\"0\",\"updateTime\":\"0\"}');

SET FOREIGN_KEY_CHECKS = 1;
