spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 9999
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

management:
  endpoint:
    prometheus:
      enabled: true

  endpoints:
    web:
      exposure:
        include: prometheus